version: '2.1'
services:

  database:
    container_name: database
    image: postgres
    restart: always
    ports:
      - 5432:5432
    user: "postgres"
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "db"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 3s
      timeout: 1s
      retries: 20
    networks:
      - networkgroup-backend

  backend:
    container_name: app-backend
    build:
      context: ./
      dockerfile: DockerfileBackend
    image: app-backend
    depends_on:
      database:
        condition: service_healthy
    ports:
      - 8443:8443
    networks:
      - networkgroup-backend

  frontend:
    container_name: app-frontend
    build:
      context: ./frontend
      dockerfile: DockerfileFrontend
    image: app-frontend
    depends_on:
      - backend
    ports:
      - 80:80
    networks:
      - networkgroup-client

networks:
  networkgroup-client:
  networkgroup-backend:
