apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  name: ecohack-networkgroup-client
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              io.kompose.network/ecohack-networkgroup-client: "true"
  podSelector:
    matchLabels:
      io.kompose.network/ecohack-networkgroup-client: "true"
